# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(531, 776)
        Calculator.setMinimumSize(QtCore.QSize(531, 776))
        Calculator.setMaximumSize(QtCore.QSize(531, 776))
        Calculator.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 491, 711))
        self.frame.setStyleSheet("background-color: rgb(170, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_d5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d5.setGeometry(QtCore.QRect(130, 360, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d5.setFont(font)
        self.pushButton_d5.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d5.setObjectName("pushButton_d5")
        self.buttonGroup = QtWidgets.QButtonGroup(Calculator)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_d5)
        self.pushButton_d8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d8.setGeometry(QtCore.QRect(130, 250, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d8.setFont(font)
        self.pushButton_d8.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d8.setObjectName("pushButton_d8")
        self.buttonGroup.addButton(self.pushButton_d8)
        self.pushButton_clr = QtWidgets.QPushButton(self.frame)
        self.pushButton_clr.setGeometry(QtCore.QRect(20, 140, 221, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_clr.setFont(font)
        self.pushButton_clr.setStyleSheet("background-color: red\n"
"")
        self.pushButton_clr.setObjectName("pushButton_clr")
        self.pushButton_d2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d2.setGeometry(QtCore.QRect(130, 470, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d2.setFont(font)
        self.pushButton_d2.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d2.setObjectName("pushButton_d2")
        self.buttonGroup.addButton(self.pushButton_d2)
        self.pushButton_add = QtWidgets.QPushButton(self.frame)
        self.pushButton_add.setGeometry(QtCore.QRect(350, 580, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.pushButton_add.setAutoDefault(False)
        self.pushButton_add.setDefault(False)
        self.pushButton_add.setFlat(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_d0 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d0.setGeometry(QtCore.QRect(20, 580, 221, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d0.setFont(font)
        self.pushButton_d0.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d0.setObjectName("pushButton_d0")
        self.buttonGroup.addButton(self.pushButton_d0)
        self.pushButton_eq = QtWidgets.QPushButton(self.frame)
        self.pushButton_eq.setGeometry(QtCore.QRect(240, 580, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setStyleSheet("background-color: rgb(85, 0, 255)")
        self.pushButton_eq.setAutoDefault(False)
        self.pushButton_eq.setDefault(False)
        self.pushButton_eq.setFlat(False)
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.pushButton_d7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d7.setGeometry(QtCore.QRect(20, 250, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d7.setFont(font)
        self.pushButton_d7.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d7.setObjectName("pushButton_d7")
        self.buttonGroup.addButton(self.pushButton_d7)
        self.pushButton_mul = QtWidgets.QPushButton(self.frame)
        self.pushButton_mul.setGeometry(QtCore.QRect(350, 360, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.pushButton_mul.setAutoDefault(False)
        self.pushButton_mul.setDefault(False)
        self.pushButton_mul.setFlat(False)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_del = QtWidgets.QPushButton(self.frame)
        self.pushButton_del.setGeometry(QtCore.QRect(240, 140, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(24)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("background-color: rgb(85, 0, 255)")
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_d6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d6.setGeometry(QtCore.QRect(240, 360, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d6.setFont(font)
        self.pushButton_d6.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d6.setObjectName("pushButton_d6")
        self.buttonGroup.addButton(self.pushButton_d6)
        self.pushButton_d4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d4.setGeometry(QtCore.QRect(20, 360, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d4.setFont(font)
        self.pushButton_d4.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d4.setObjectName("pushButton_d4")
        self.buttonGroup.addButton(self.pushButton_d4)
        self.pushButton_sub = QtWidgets.QPushButton(self.frame)
        self.pushButton_sub.setGeometry(QtCore.QRect(350, 470, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.pushButton_sub.setAutoDefault(False)
        self.pushButton_sub.setDefault(False)
        self.pushButton_sub.setFlat(False)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_d3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d3.setGeometry(QtCore.QRect(240, 470, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d3.setFont(font)
        self.pushButton_d3.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d3.setObjectName("pushButton_d3")
        self.buttonGroup.addButton(self.pushButton_d3)
        self.pushButton_d1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d1.setGeometry(QtCore.QRect(20, 470, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d1.setFont(font)
        self.pushButton_d1.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d1.setObjectName("pushButton_d1")
        self.buttonGroup.addButton(self.pushButton_d1)
        self.pushButton_mod = QtWidgets.QPushButton(self.frame)
        self.pushButton_mod.setGeometry(QtCore.QRect(350, 140, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_mod.setFont(font)
        self.pushButton_mod.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.pushButton_mod.setObjectName("pushButton_mod")
        self.pushButton_div = QtWidgets.QPushButton(self.frame)
        self.pushButton_div.setGeometry(QtCore.QRect(350, 250, 111, 111))
        font = QtGui.QFont()
        font.setFamily("AnjaliOldLipi")
        font.setPointSize(20)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.pushButton_div.setAutoDefault(False)
        self.pushButton_div.setDefault(False)
        self.pushButton_div.setFlat(False)
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_d9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_d9.setGeometry(QtCore.QRect(240, 250, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Ani")
        font.setPointSize(26)
        font.setItalic(False)
        self.pushButton_d9.setFont(font)
        self.pushButton_d9.setStyleSheet("background-color: rgb(0, 255, 255)")
        self.pushButton_d9.setObjectName("pushButton_d9")
        self.buttonGroup.addButton(self.pushButton_d9)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 243, 71)")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 29))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(Calculator)
        self.actionAbout.setObjectName("actionAbout")
        self.menuInfo.addAction(self.actionAbout)
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Matf Calculator"))
        self.pushButton_d5.setText(_translate("Calculator", "5"))
        self.pushButton_d8.setText(_translate("Calculator", "8"))
        self.pushButton_clr.setText(_translate("Calculator", "C"))
        self.pushButton_d2.setText(_translate("Calculator", "2"))
        self.pushButton_add.setWhatsThis(_translate("Calculator", "control button"))
        self.pushButton_add.setText(_translate("Calculator", "+"))
        self.pushButton_d0.setText(_translate("Calculator", "0"))
        self.pushButton_eq.setWhatsThis(_translate("Calculator", "control button"))
        self.pushButton_eq.setText(_translate("Calculator", "="))
        self.pushButton_d7.setText(_translate("Calculator", "7"))
        self.pushButton_mul.setWhatsThis(_translate("Calculator", "control button"))
        self.pushButton_mul.setText(_translate("Calculator", "x"))
        self.pushButton_del.setText(_translate("Calculator", "DEL"))
        self.pushButton_d6.setText(_translate("Calculator", "6"))
        self.pushButton_d4.setText(_translate("Calculator", "4"))
        self.pushButton_sub.setWhatsThis(_translate("Calculator", "control button"))
        self.pushButton_sub.setText(_translate("Calculator", "-"))
        self.pushButton_d3.setText(_translate("Calculator", "3"))
        self.pushButton_d1.setText(_translate("Calculator", "1"))
        self.pushButton_mod.setText(_translate("Calculator", "%"))
        self.pushButton_div.setWhatsThis(_translate("Calculator", "control button"))
        self.pushButton_div.setText(_translate("Calculator", "/"))
        self.pushButton_d9.setText(_translate("Calculator", "9"))
        self.menuInfo.setTitle(_translate("Calculator", "Info"))
        self.actionAbout.setText(_translate("Calculator", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
